[versions]
# Project
project-minSdk = "24"
project-compileSdk = "36"
project-targetSdk = "36"
project-versionCode = "120"
project-versionName = "1.2.0"

# Plugins
agp = "8.11.1"
kotlin = "2.2.0"
composePlugin = "1.10.0"
firebase = "4.4.3"
firebase-crashlytics = "3.0.6"

# Libs
androidx-appcompat = "1.7.1"
androidx-activity = "1.10.1"
material3 = "1.9.0"
material-icons = "1.7.3"

kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinxDatetime = "0.7.1"

koin = "4.1.0"

ktor = "3.2.3"

firebaseBom = "34.1.0"

voyager = "1.0.1"
decompose = "3.3.0"
decompose-coroutines = "2.5.0"

featherIcons = "1.1.1"
dataStore = "1.1.7"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composePlugin" }
compose-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "composePlugin" }
compose-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composePlugin" }
compose-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composePlugin" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose-multiplatform = { module = "io.insert-koin:koin-compose", version.ref = "koin" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }

voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-experimental = { module = "com.arkivanov.decompose:extensions-compose-experimental", version.ref = "decompose" }
decompose-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "decompose-coroutines" }

icons-feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "featherIcons" }

datastore = { module = "androidx.datastore:datastore", version.ref = "dataStore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

[bundles]
koin = [
    "koin-core",
    "koin-compose-multiplatform",
]

voyager = [
    "voyager-screenModel",
    "voyager-navigator",
]

decompose = [
    "decompose",
    "decompose-extensions",
    "decompose-experimental",
    "decompose-coroutines",
]

ktor = [
    "ktor-core",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
]

datastore = [
    "datastore",
    "datastore-preferences",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

firebase = { id = "com.google.gms.google-services", version.ref = "firebase" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }